[hostname]
ssh_only = false
format = '[Arch](bold #5e1ef5) '
trim_at = "."
disabled = false

[character]                          
success_symbol = "[ïŒƒ ](bold #5d3fd3)" 
error_symbol = "[âœ˜ ](bold red)"

[directory]
read_only = " î‚¢"
truncation_length = 10
truncate_to_repo = true 
truncation_symbol = "â€¦/"
style = "bold italic blue"

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "bold italic red"

[aws]
format = "ï„ [$symbol]($style)"
symbol = "îŒ½  "

[conda]
format = "ï„ [$symbol]($style)"
symbol = "ï„Œ "

[dart]
format = "ï„ [$symbol]($style)"
symbol = "î˜ "

[docker_context]
symbol = "ïŒˆ "
format = "Â» [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[elixir]
format = "ï„ [$symbol]($style)"
symbol = "î‰µ "

[elm]
format = "ï„ [$symbol]($style)"
symbol = "î˜¬ "

[git_branch]
symbol = "ï˜ "

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "ï± "
ahead = "ó±¡® Ã—${count} "
behind = "ó°´» Ã—${count} "
diverged = "ó±¡·  ó±¡®  Ã—${ahead_count} ó°´» Ã—${behind_count} "
untracked = "ó°ˆ› Ã—${count} "
stashed = "îµµ "
modified = "ïŸ Ã—${count} "
staged = "ï‘ Ã—${count} "
renamed = "ó°‘• Ã—${count} "
deleted = "ó°†´ Ã—${count} "
style = "bright-white"
format = "$all_status$ahead_behind"

[golang]
style = 'blue'
format = "ï„ [$symbol GO ]($style)"
symbol = "î˜§"

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "
format = 'Â» [${symbol}java (\($virtualenv\) )]($style)'

[julia]
format = "ï„ [$symbol]($style)"
symbol = "î˜¤ "

[memory_usage]
format = "ï„ [$symbol]($style)"
symbol = "î¿… "

[nim]
format = "ï„ [$symbol]($style)"
symbol = "î¡ "

[nix_shell]
format = "ï„ [$symbol]($style)"
symbol = "ï‹œ "

[package]
disabled = true

[perl]
symbol = "î© "
format = "ï„ [$symbol]($style)"

[php]
symbol = "î˜ˆ "
format = "ï„ [$symbol php ]($style)"

[python]
symbol = "î˜† "
format = 'Â» [${symbol}python (\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]

[ruby]
symbol = "îˆ¾ "
format = "ï„ [$symbol]($style)"

[rust]
style = 'blue'
format = "ï„ [$symbol rust ]($style)"
symbol = "î¨"

[scala]
symbol = "îœ· "
format = "ï„ [$symbol]($style)"

[shlvl]
symbol = "ï„  "
format = "ï„ [$symbol]($style)"

[swift]
symbol = "ï¯£ "
format = "ï„ [$symbol]($style)"

[nodejs]
format = "Â» [î´ Node.js](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[directory.substitutions]
"Documents" = "ğŸ— "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
